export const electionAbi = [
  {
    type: "function",
    name: "addCandidate",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_description", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addToWhiteList",
    inputs: [
      {
        name: "toAccounts",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "calculateFinalResult",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createdAt",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "electionId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "electionInfo",
    inputs: [],
    outputs: [
      { name: "startTime", type: "uint64", internalType: "uint64" },
      { name: "endTime", type: "uint64", internalType: "uint64" },
      { name: "electionId", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "endElection",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "factoryContractAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBallotAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCandidateList",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Election.Candidate[]",
        components: [
          {
            name: "candidateId",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "name", type: "string", internalType: "string" },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIsElectionManuallyEnded",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIsResultsDeclared",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWinnersList",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVoted",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "_isPrivate", type: "bool", internalType: "bool" },
      {
        name: "_factoryAddress",
        type: "address",
        internalType: "address",
      },
      { name: "_owner", type: "address", internalType: "address" },
      {
        name: "_electionInfo",
        type: "tuple",
        internalType: "struct Election.ElectionInfo",
        components: [
          { name: "startTime", type: "uint64", internalType: "uint64" },
          { name: "endTime", type: "uint64", internalType: "uint64" },
          {
            name: "electionId",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "name", type: "string", internalType: "string" },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
        ],
      },
      {
        name: "_candidates",
        type: "tuple[]",
        internalType: "struct Election.Candidate[]",
        components: [
          {
            name: "candidateId",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "name", type: "string", internalType: "string" },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
        ],
      },
      { name: "_resultType", type: "uint8", internalType: "uint8" },
      { name: "_ballot", type: "address", internalType: "address" },
      {
        name: "_resultCalculator",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isElectionEnded",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPrivate",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isWhitelisted",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removeCandidate",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resultType",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalVoters",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userVote",
    inputs: [{ name: "voteArr", type: "uint256[]", internalType: "uint256[]" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "AddCandidate",
    inputs: [
      {
        name: "name",
        type: "string",
        indexed: true,
        internalType: "string",
      },
      {
        name: "description",
        type: "string",
        indexed: true,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CalculateFinalResult",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "CastVote",
    inputs: [
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EndElection",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemoveCandidate",
    inputs: [
      {
        name: "candidateId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "Election_BallotIsNotIntialized", inputs: [] },
  {
    type: "error",
    name: "Election_CandidateAlreadyRemoved",
    inputs: [{ name: "candidateId", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "Election_ElectionActive", inputs: [] },
  { type: "error", name: "Election_ElectionEnded", inputs: [] },
  { type: "error", name: "Election_ElectionInactive", inputs: [] },
  { type: "error", name: "Election_InvalidCandidateID", inputs: [] },
  {
    type: "error",
    name: "Election_InvalidCandidatesLengthAfterRemoval",
    inputs: [],
  },
  {
    type: "error",
    name: "Election_InvalidVoteArrayLength",
    inputs: [],
  },
  { type: "error", name: "Election_NotOwner", inputs: [] },
  { type: "error", name: "Election_PrivateElection", inputs: [] },
  {
    type: "error",
    name: "Election_ResultsHaveAlreadyBeenDeclared",
    inputs: [{ name: "winners", type: "uint256[]", internalType: "uint256[]" }],
  },
  {
    type: "error",
    name: "Election_UnauthorizedDeployment",
    inputs: [
      {
        name: "factoryAddress",
        type: "address",
        internalType: "address",
      },
    ],
  },
  { type: "error", name: "Election_UserHasAlreadyVoted", inputs: [] },
  { type: "error", name: "Election_VotesUnavailable", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
];
